---

- hosts: all
  become: yes
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2

  - name: install libapache on ubuntu
    apt:
      name: libapache2-mod-php

  - name: enable apache2 package
    service:
      name: apache2
      state: started

- hosts: prometheus_host
  become: yes
  tasks:

  - name: install prometheus
    apt:
      name: prometheus
      state: latest

  - name: enable the prometheus
    service:
      name: prometheus
      state: started
